name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-cloudrun.yml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION || 'us-central1' }}
  SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE || 'mcd-admin-backend' }}
  IMAGE: ${{ secrets.GAR_IMAGE || 'backend' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Enable required APIs
        run: |
          gcloud services enable artifactregistry.googleapis.com run.googleapis.com cloudbuild.googleapis.com --quiet

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Create Artifact Registry repository if needed
        run: |
          gcloud artifacts repositories describe mcd-admin --location=${{ env.REGION }} || \
          gcloud artifacts repositories create mcd-admin --repository-format=docker --location=${{ env.REGION }} --description="MCD Admin Docker images"

      - name: Build and push image
        working-directory: backend
        run: |
          IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/mcd-admin/${{ env.IMAGE }}:$(echo $GITHUB_SHA | head -c7)
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY_RAW: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: |
          # Escape newlines in private key for environment variable
          GOOGLE_PRIVATE_KEY_ESC=$(echo "$GOOGLE_PRIVATE_KEY_RAW" | sed ':a;N;$!ba;s/\n/\\n/g')
          
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image "$IMAGE_URI" \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --max-instances 3 \
            --memory 512Mi \
            --port 3001 \
            --set-env-vars "NODE_ENV=production,JWT_SECRET=${JWT_SECRET},CORS_ORIGIN=${{ vars.CORS_ORIGIN || 'https://scopmn8-dot.github.io' }},GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL},GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY_ESC}"

      - name: Show service URL
        run: gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format='value(status.url)'
